%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Ioannis\OneDrive\HFIE\PA_P1\Wetterstation\MET Office Weather Data.csv
%
% Auto-generated by MATLAB on 21-Sep-2020 17:03:17

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["year", "month", "tmax", "tmin", "af", "rain", "sun", "station"];
opts.VariableTypes = ["double", "double", "double", "double", "categorical", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["af", "station"], "EmptyFieldRule", "auto");

% Import the data
weatherD = readtable("C:\Users\Ioannis\OneDrive\HFIE\PA_P1\Wetterstation\MET Office Weather Data.csv", opts);

%% Clear temporary variables
clear opts

%% Aufgabe 3
wDfixed = rmmissing(weatherD);
removedRows = height(weatherD) - height(wDfixed);

%% Aufgabe 4a
sortedD = sortrows(wDfixed, [1 2]);             % select sort criteria by column index
sortedD = sortrows(wDfixed, {'year', 'month'}); % select sort criteriy by column name
plot( sortedD.year, sortedD.tmax);

%% Aufgabe 5a
% mit summary können wir das einfach ablesen
groupSum = groupsummary(wDfixed, 'station');

[maxGroupCount, index] = max(groupSum.GroupCount);
maxStation = groupSum.station(index);
maxStationD = wDfixed(wDfixed.station==maxStation,:);

%% Aufgabe 6a und 7a
wDfixed.AvgTemp = (wDfixed.tmax + wDfixed.tmin)/2;

%in case more than one column is selected we need {}
meanTemp = groupsummary( wDfixed, 'year', {'mean','median'}, {'tmax', 'tmin'} ); 
hold off; % just to avoid that the graph contains old stuff in case of reptition of the same section!
plot(meanTemp.year, meanTemp.mean_tmax, "-*");
hold on;
plot(meanTemp.year, meanTemp.median_tmax, "-+");    
plot(meanTemp.year, meanTemp.mean_tmin, "-^" );
plot(meanTemp.year, meanTemp.median_tmin, "-<" );


%% Aufgabe 8a
meanTempPerStation = groupsummary(wDfixed, {'station', 'year'}, {'mean', 'median'}, {'tmin', 'tmax'});
[minTs, idxMin] = min( meanTempPerStation.mean_tmin );
[maxTs, idxMax] = max( meanTempPerStation.mean_tmax );
minS = wDfixed.station(idxMin);
maxS = wDfixed.station(idxMax);

%% Aufgabe 9a

y = wDfixed( wDfixed.station == maxS, 'rain');
x = wDfixed( wDfixed.station == maxS, 'tmax');
scatter(x.tmax, y.rain );

%% Aufgabe 10a
minD = wDfixed( wDfixed.station == minS, :  );
maxD = wDfixed( wDfixed.station == maxS, : );

ismember( minD, wDfixed );
minAndMaxD = union( minD, maxD);

boxplot(minAndMaxD.tmax, minAndMaxD.station);