%% Import data from text file
% Script for importing data from the following text file:
%
% filename: C:\Users\rolfl\OneDrive - GIBZ\HFIE\ProzessSimulationMatlab\Übungen\MET Office Weather Data.csv
%
% Auto-generated by MATLAB on 07-Sep-2020 11:06:05
%

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["year", "month", "tmax", "tmin", "af", "rain", "sun", "station"];
opts.VariableTypes = ["int16", "int16", "double", "double", "categorical", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["af", "station"], "EmptyFieldRule", "auto");

% Import the data
weatherD = readtable("C:\Users\Ioannis\Desktop\Github_Repos\MATLAB\Wetterstation\MET_Office_Weather_Data.csv", opts);


%% Clear temporary variables
clear opts

wDfixed = rmmissing(weatherD);
removedRows = height(weatherD) - height(wDfixed);



%%

yearlyMeanPerStation = groupsummary(wDfixed, {'station', 'year'}, {'mean', 'median'}, {'tmin', 'tmax'});
monthlyMeanPerStation = groupsummary(wDfixed, {'station', 'year', 'month'}, {'mean', 'median'}, {'tmin', 'tmax'});
monthlyMean  = groupsummary(wDfixed, {'month'}, {'mean', 'median'}, {'tmin', 'tmax', 'rain', 'sun'});

%% Aufgabe 1
boxplot( monthlyMeanPerStation.median_tmin, monthlyMeanPerStation.month);
xlabel("month");
ylabel("median tmin");
title("tmin variation per month from 1942 to 2020")


%% Aufgabe 2
bar(monthlyMean.median_rain);
xlabel("month")
ylabel("rain in mm")
title("median rain per month")

%% Aufgabe 3
ylim([50 90])
%with these limits, the diagram suggests that there is a huge difference in
%rain fall between Nov and May which is not really true
%hence the selection of limits influences the intepretation of the diagram!

%% Aufgabe 4
data = [monthlyMean.median_tmin monthlyMean.median_tmax];
bar( data );
hold on;
plot( data );
legend("median tmin", "median tmax");
hold off;

%% Aufgabe 5
hold off
yyaxis left
ylim([0 100])
plot( monthlyMean.median_rain, "color", "b", "linestyle","-." );
ylabel("sunshine rain");
hold on
yyaxis right
plot( monthlyMean.median_sun, "color", "r", "linestyle",":" );
ylabel("sun shine hours");
hold off;
xlabel("month")
title("rain and sunshine over the year")

%% Aufgabe 6

hold off
tiledlayout(3,1);
%boxplot( monthlyMeanPerStation.mean_tmax, monthlyMeanPerStation.month );
l1 = nexttile;

%aus Aufgabe 1
boxplot(l1, monthlyMeanPerStation.median_tmin, monthlyMeanPerStation.month);
xlabel(l1, "month");
ylabel(l1, "median tmin");
title(l1, "tmin variation per month from 1942 to 2020")

%aus Aufgabe 2
l2 = nexttile;
bar(l2, monthlyMean.median_rain);
xlabel(l2, "month");
ylabel(l2, "rain in mm");
title(l2, "median rain per month");

%aus Aufgabe 5
l3 = nexttile;
yyaxis left

plot(l3, monthlyMean.median_rain, "color", "b", "linestyle","-." );
ylabel(l3,"sunshine rain");
hold on
yyaxis right
plot( l3, monthlyMean.median_sun, "color", "r", "linestyle",":" );
ylabel(l3,"sun shine hours");
hold off;
xlabel(l3,"month")
title(l3,"rain and sunshine over the year")
tiledlayout(1,1)


%% Aufgabe 6

h = histogram( yearlyMeanPerStation.median_tmin );
title( "Median temperatur tmin der Messstationen über alle Jahre" );
xlabel("Temperatur");
ylabel("Häufigkeit");

%h.Normalization = "probability";
